services:
  web:
    build: .
    command: sh -c "/app/wait-for-db.sh && python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - backend_network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - web
    networks:
      - backend_network

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend_network

  redis:
    image: redis
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    networks:
      - backend_network

  celery_beat:
    build: .
    command: celery -A config beat --loglevel=info -s /var/run/celery/celerybeat-schedule
    user: "1000:1000"
    env_file: .env
    volumes:
      - ./celery_beat:/app/celery_beat
    depends_on:
      - redis
      - db

  celery_worker:
    build: .
    command: celery -A config worker --loglevel=INFO
    user: "1000:1000"
    env_file: .env
    depends_on:
      - redis
      - db

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  redis_data:
