services:
  web:
    build: .
    command: sh -c "/app/wait-for-db.sh && python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health/" ]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - .:/app
      - static_volume:/app/static
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
    ports:
      -
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - backend_network

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web
    env_file:
      - .env

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend_network

  redis:
    image: redis:alpine
    networks:
      - backend_network

  celery_worker:
    build: .
    command: celery -A config worker --uid=1000 --gid=1000 -l INFO
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    networks:
      - backend_network

  celery_beat:
    build: .
    command: celery -A config beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  redis_volume:
