services:
  web:
    build: .
    command: sh -c "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started


  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - web


  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    image: redis
    expose:
      - "6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - redis_data:/data



  celery_beat:
    build: .
    command: celery -A config beat --loglevel=info
    env_file: .env
    volumes:
      - ./celery_beat:/app/celery_beat
    depends_on:
      - redis
      - db

  celery_worker:
    build: .
    command: celery -A config worker --loglevel=INFO
    env_file: .env
    depends_on:
      - redis
      - db

networks:
  default:

volumes:
  postgres_data:
  static_volume:
  redis_data:
