# Generated by Django 5.1.6 on 2025-02-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=200, verbose_name='Название курса')),
                ('preview', models.ImageField(blank=True, help_text='Превью для курса', null=True, upload_to='course/preview/', verbose_name='Превью')),
                ('description', models.TextField(verbose_name='Описание')),
                ('video_url', models.URLField(verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
